  server:
    port: 3000

  springdoc:
    version: '1.0.0'
    api-docs:
      path: /api-docs
    default-consumes-media-type: application/json #요청 헤더의 content 타입
    default-produces-media-type: application/json #응답 헤더의 content 타입
    swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      path: /apidocs.html
      disable-swagger-default-url: true
    paths-to-match:
      - /api/**